language: python
python:
  - "3.7"
install:
  - pip install coverage==4.3
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
  - pip install codacy-coverage
script:
  - coverage run -m pytest --cov-report=xml --cov=.

after_success:
  - codecov
  - python-codacy-coverage -r coverage.xml
